services:
    antifier:
        privileged: true
        tty: true
        build:
            context: ./
            dockerfile: ./Dockerfile
        working_dir: /antifier
        stop_grace_period: 10s
        stdin_open: true
        command: ["python3", "antifier.py"]
        volumes:
            - ./:/antifier
            - /run/dbus:/run/dbus
#            - /dev/serial/by-id/usb-Dynastream_Innovations_ANT_USB-m_Stick_106-if00-port0:/dev/ttyUSB0
        devices:
            - /dev/serial/by-id/usb-Dynastream_Innovations_ANT_USB-m_Stick_106-if00-port0:/dev/ttyUSB0
